In [4]:
# core engine that talks to Chrome
from selenium import webdriver

# Helps you locate elements on page
from selenium.webdriver.common.by import By

# Manages how ChromeDriver runs (background service)
from selenium.webdriver.chrome.service import Service

# Automatically installs correct ChromeDriver
from webdriver_manager.chrome import ChromeDriverManager

In [ ]:
service = Service(ChromeDriverManager().install())
# ChromeDriverManager().install() → downloads driver
# Service(...) → wraps it for Selenium

In [8]:
driver = webdriver.Chrome(service=service)
# Launches Chrome
# Creates driver → your control object

driver.get("https://www.google.com")
# Chrome opens Google
# Selenium waits until page loads

search_box = driver.find_element(By.NAME, "q")
# find_element → locate something on page
# By.NAME → search using HTML attribute
# "q" → Google search input name

search_box.send_keys("Real Python Selenium")
# Simulates keyboard typing

search_box.submit()
# Pressing ENTER

import time
time.sleep(10)

driver.quit()
# Closes Chrome properly
# Prevents memory leaks

In [16]:
# role → WHAT the element is. “What kind of UI element this is”
# aria-label → WHAT it’s called. “A readable name for the element”


from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.keys import Keys
import time

# Setup Chrome
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

# Open website
driver.get("https://www.superdrug.com")

time.sleep(3)

# Handle cookie popup (if present)
try:
    accept_btn = driver.find_element(By.XPATH, "//button[contains(text(),'Accept')]")
    accept_btn.click()
    time.sleep(1)
except:
    pass

# 🔍 Use combined attributes (role + aria-label)
search_box = driver.find_element(
    By.XPATH, "//input[@role='combobox' and @aria-label='Search']"
)

# Activate input
search_box.click()

# Enter EAN
search_box.send_keys("3600523966905")

time.sleep(1)

# Submit search
search_box.send_keys(Keys.RETURN)

time.sleep(5)

driver.quit()

In [17]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
wait = WebDriverWait(driver, 10)

driver.get("https://www.superdrug.com")

# Accept cookies
try:
    wait.until(EC.element_to_be_clickable((By.XPATH, "//button[contains(text(),'Accept')]"))).click()
except:
    pass

# 🔍 Search
search_box = wait.until(
    EC.presence_of_element_located((By.XPATH, "//input[@role='combobox' and @aria-label='Search']"))
)

search_box.click()
search_box.send_keys("3600523966905")
search_box.send_keys(Keys.RETURN)

# Wait for results to load
wait.until(EC.presence_of_element_located((By.XPATH, "//a[contains(@class,'cx-product-name')]")))

# Remove Toky popup
driver.execute_script("""
var elem = document.getElementById('toky_container');
if (elem) { elem.remove(); }
""")

# 🧠 Get first product safely
products = driver.find_elements(By.XPATH, "//a[contains(@class,'cx-product-name')]")

if not products:
    print("No products found")
    driver.quit()
    exit()

first_product = products[0]
product_name = first_product.text.strip()

# Scroll + click
driver.execute_script("arguments[0].scrollIntoView();", first_product)
wait.until(EC.element_to_be_clickable(first_product)).click()

# Wait for product page
wait.until(EC.presence_of_element_located((By.TAG_NAME, "body")))

# 🧠 Extract promotion
try:
    promo_label = wait.until(
        EC.presence_of_element_located((By.XPATH, "//span[contains(@class,'promotion__offer-label')]"))
    ).text
except:
    promo_label = "No offer label"

try:
    promo_detail = driver.find_element(
        By.XPATH, "//div[contains(@class,'promotion__label')]"
    ).text
except:
    promo_detail = "No detailed offer"

print("Product Name:", product_name)
print("Offer Label:", promo_label)
print("Offer Detail:", promo_detail)

driver.quit()

ElementClickInterceptedException: Message: element click intercepted: Element <a e2clickimpression="" class="cx-product-name" href="/hair/shampoo/dry-shampoo/loreal-paris-elvive-dream-lengths-air-volume-dry-shampoo-150ml/p/804300">...</a> is not clickable at point (374, 31). Other element would receive the click: <div class="recent-searches">...</div>
  (Session info: chrome=147.0.7727.102); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#elementclickinterceptedexception
Stacktrace:
0   chromedriver                        0x000000010146debc cxxbridge1$str$ptr + 3213376
1   chromedriver                        0x0000000101465e8c cxxbridge1$str$ptr + 3180560
2   chromedriver                        0x0000000100f2b8d4 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 75096
3   chromedriver                        0x0000000100f79570 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 393716
4   chromedriver                        0x0000000100f77a98 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 386844
5   chromedriver                        0x0000000100f75800 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 377988
6   chromedriver                        0x0000000100f74ba0 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 374820
7   chromedriver                        0x0000000100f6ad04 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 334216
8   chromedriver                        0x0000000100f6a780 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 332804
9   chromedriver                        0x0000000100fb384c _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 632016
10  chromedriver                        0x0000000100f6927c _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 327424
11  chromedriver                        0x000000010142bf60 cxxbridge1$str$ptr + 2943204
12  chromedriver                        0x000000010142f744 cxxbridge1$str$ptr + 2957512
13  chromedriver                        0x0000000101410e50 cxxbridge1$str$ptr + 2832340
14  chromedriver                        0x000000010142ffc4 cxxbridge1$str$ptr + 2959688
15  chromedriver                        0x0000000101401828 cxxbridge1$str$ptr + 2769324
16  chromedriver                        0x0000000101454920 cxxbridge1$str$ptr + 3109540
17  chromedriver                        0x0000000101454a9c cxxbridge1$str$ptr + 3109920
18  chromedriver                        0x0000000101465ae4 cxxbridge1$str$ptr + 3179624
19  libsystem_pthread.dylib             0x000000018a4b2c0c _pthread_start + 136
20  libsystem_pthread.dylib             0x000000018a4adb80 thread_start + 8

In [18]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# 🔒 Disable browser notifications
chrome_options = Options()
chrome_options.add_argument("--disable-notifications")
chrome_options.add_experimental_option(
    "prefs", {"profile.default_content_setting_values.notifications": 2}
)

# 🚀 Start driver
driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=chrome_options
)

wait = WebDriverWait(driver, 10)

# 🌐 Open site
driver.get("https://www.superdrug.com")

# 🍪 Accept cookies
try:
    wait.until(EC.element_to_be_clickable(
        (By.XPATH, "//button[contains(text(),'Accept')]"))
    ).click()
except:
    pass

# 🔍 Find search box
search_box = wait.until(
    EC.presence_of_element_located(
        (By.XPATH, "//input[@role='combobox' and @aria-label='Search']")
    )
)

search_box.click()
search_box.send_keys("3600523966905")
search_box.send_keys(Keys.RETURN)

# ⏳ Wait for results
wait.until(EC.presence_of_element_located(
    (By.XPATH, "//a[contains(@class,'cx-product-name')]"))
)

# ❌ Remove Toky popup
driver.execute_script("""
var elem = document.getElementById('toky_container');
if (elem) { elem.remove(); }
""")

# 🧠 Get first product safely
products = driver.find_elements(By.XPATH, "//a[contains(@class,'cx-product-name')]")

if not products:
    print("No products found")
    driver.quit()
    exit()

first_product = products[0]
product_name = first_product.text.strip()

# 📍 Scroll into view + click
driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", first_product)

wait.until(EC.element_to_be_clickable(first_product)).click()

# ⏳ Wait for product page
wait.until(EC.presence_of_element_located((By.TAG_NAME, "body")))

# 🎯 Extract promotion details
try:
    promo_label = wait.until(
        EC.presence_of_element_located(
            (By.XPATH, "//span[contains(@class,'promotion__offer-label')]")
        )
    ).text
except:
    promo_label = "No offer label"

try:
    promo_detail = driver.find_element(
        By.XPATH, "//div[contains(@class,'promotion__label')]"
    ).text
except:
    promo_detail = "No detailed offer"

# 🧾 Output
print("Product Name:", product_name)
print("Offer Label:", promo_label)
print("Offer Detail:", promo_detail)

driver.quit()

ElementClickInterceptedException: Message: element click intercepted: Element <a e2clickimpression="" class="cx-product-name" href="/hair/shampoo/dry-shampoo/loreal-paris-elvive-dream-lengths-air-volume-dry-shampoo-150ml/p/804300">...</a> is not clickable at point (374, 345). Other element would receive the click: <div class="backdrop backdrop--opened-box backdrop--opened-suggestions"></div>
  (Session info: chrome=147.0.7727.102); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#elementclickinterceptedexception
Stacktrace:
0   chromedriver                        0x0000000103365ebc cxxbridge1$str$ptr + 3213376
1   chromedriver                        0x000000010335de8c cxxbridge1$str$ptr + 3180560
2   chromedriver                        0x0000000102e238d4 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 75096
3   chromedriver                        0x0000000102e71570 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 393716
4   chromedriver                        0x0000000102e6fa98 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 386844
5   chromedriver                        0x0000000102e6d800 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 377988
6   chromedriver                        0x0000000102e6cba0 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 374820
7   chromedriver                        0x0000000102e62d04 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 334216
8   chromedriver                        0x0000000102e62780 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 332804
9   chromedriver                        0x0000000102eab84c _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 632016
10  chromedriver                        0x0000000102e6127c _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 327424
11  chromedriver                        0x0000000103323f60 cxxbridge1$str$ptr + 2943204
12  chromedriver                        0x0000000103327744 cxxbridge1$str$ptr + 2957512
13  chromedriver                        0x0000000103308e50 cxxbridge1$str$ptr + 2832340
14  chromedriver                        0x0000000103327fc4 cxxbridge1$str$ptr + 2959688
15  chromedriver                        0x00000001032f9828 cxxbridge1$str$ptr + 2769324
16  chromedriver                        0x000000010334c920 cxxbridge1$str$ptr + 3109540
17  chromedriver                        0x000000010334ca9c cxxbridge1$str$ptr + 3109920
18  chromedriver                        0x000000010335dae4 cxxbridge1$str$ptr + 3179624
19  libsystem_pthread.dylib             0x000000018a4b2c0c _pthread_start + 136
20  libsystem_pthread.dylib             0x000000018a4adb80 thread_start + 8

In [20]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

import pandas as pd
import time

# -------------------------------
# 🔒 Setup Chrome
# -------------------------------
chrome_options = Options()
chrome_options.add_argument("--disable-notifications")
chrome_options.add_experimental_option(
    "prefs", {"profile.default_content_setting_values.notifications": 2}
)

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=chrome_options
)

wait = WebDriverWait(driver, 15)

# -------------------------------
# 🔍 Input
# -------------------------------
ean = "3600523966905"

# -------------------------------
# 🌐 Open Website
# -------------------------------
driver.get("https://www.superdrug.com")

# Accept cookies (if present)
try:
    wait.until(EC.element_to_be_clickable(
        (By.XPATH, "//button[contains(text(),'Accept')]"))
    ).click()
except:
    pass

# -------------------------------
# 🔍 Perform Search
# -------------------------------
search_box = wait.until(
    EC.presence_of_element_located(
        (By.XPATH, "//input[@role='combobox' and @aria-label='Search']")
    )
)

search_box.clear()
search_box.send_keys(ean)
search_box.send_keys(Keys.RETURN)

# Wait for results
wait.until(EC.presence_of_element_located(
    (By.XPATH, "//a[contains(@class,'cx-product-name')]"))
)

# Remove chat popup if present
driver.execute_script("""
var elem = document.getElementById('toky_container');
if (elem) { elem.remove(); }
""")

# Scroll to trigger lazy loading
driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
time.sleep(3)

# -------------------------------
# 🧠 Extract data (GLOBAL LIST METHOD)
# -------------------------------

# Product names + URLs
names = driver.find_elements(By.XPATH, "//a[contains(@class,'cx-product-name')]")

# Promotion label (your first element)
labels = driver.find_elements(By.XPATH, "//span[contains(@class,'promotion__offer-label')]")

# Promotion detail (your second element)
details = driver.find_elements(By.XPATH, "//div[contains(@class,'promotion__label')]")

print("DEBUG COUNTS:")
print("Products:", len(names))
print("Labels:", len(labels))
print("Details:", len(details))

# -------------------------------
# 🔁 Map data using index
# -------------------------------
results = []

max_len = max(len(names), len(labels), len(details))

for i in range(max_len):

    # Product
    name = names[i].text.strip() if i < len(names) else "No name"
    url = names[i].get_attribute("href") if i < len(names) else "No URL"

    # Promotion
    label = labels[i].text.strip() if i < len(labels) else "No offer"
    detail = details[i].text.strip() if i < len(details) else "No detail"

    results.append({
        "EAN": ean,
        "Product Name": name,
        "URL": url,
        "Offer Label": label,
        "Offer Detail": detail
    })

# -------------------------------
# 📊 Convert to pandas
# -------------------------------
df = pd.DataFrame(results)

print("\n✅ Final Output:")
display(df.head())

driver.quit()

DEBUG COUNTS:
Products: 1
Labels: 1
Details: 1

✅ Final Output:

,EAN,Product Name,URL,Offer Label,Offer Detail
0,3600523966905,,https://www.superdrug.com/hair/shampoo/dry-sha...,,

In [ ]:
# The issue is happening because of visibility rendering

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

import pandas as pd
import time

# -------------------------------
# 🔒 Setup Chrome
# -------------------------------
chrome_options = Options()
chrome_options.add_argument("--disable-notifications")
chrome_options.add_experimental_option(
    "prefs", {"profile.default_content_setting_values.notifications": 2}
)

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=chrome_options
)

wait = WebDriverWait(driver, 15)

# -------------------------------
# 🔍 Input
# -------------------------------
# ean = "3600524049102"
ean = "3600524049102"

# -------------------------------
# 🌐 Open Website
# -------------------------------
driver.get("https://www.superdrug.com")

# Accept cookies
try:
    wait.until(EC.element_to_be_clickable(
        (By.XPATH, "//button[contains(text(),'Accept')]"))
    ).click()
except:
    pass

# -------------------------------
# 🔍 Perform Search
# -------------------------------
search_box = wait.until(
    EC.presence_of_element_located(
        (By.XPATH, "//input[@role='combobox' and @aria-label='Search']")
    )
)

search_box.clear()
search_box.send_keys(ean)
search_box.send_keys(Keys.RETURN)

# Wait for results
wait.until(EC.presence_of_element_located(
    (By.XPATH, "//a[contains(@class,'cx-product-name')]"))
)

# Remove chat popup if present
driver.execute_script("""
var elem = document.getElementById('toky_container');
if (elem) { elem.remove(); }
""")

# Scroll to trigger lazy loading (important)
driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
time.sleep(3)

# -------------------------------
# 🧠 Extract elements globally
# -------------------------------
names = driver.find_elements(By.XPATH, "//a[contains(@class,'cx-product-name')]")
labels = driver.find_elements(By.XPATH, "//span[contains(@class,'promotion__offer-label')]")
details = driver.find_elements(By.XPATH, "//div[contains(@class,'promotion__label')]")

print("DEBUG COUNTS:")
print("Products:", len(names))
print("Labels:", len(labels))
print("Details:", len(details))

# -------------------------------
# 🔁 Map using index (safe bounds)
# -------------------------------
results = []

max_len = max(len(names), len(labels), len(details))

for i in range(max_len):

    # Product name (FIX: use innerText)
    name = names[i].get_attribute("innerText").strip() if i < len(names) else "No name"

    # Product URL
    url = names[i].get_attribute("href") if i < len(names) else "No URL"

    # Promotion label (FIX: innerText)
    label = labels[i].get_attribute("innerText").strip() if i < len(labels) else "No offer"

    # Promotion detail (FIX: innerText)
    detail = details[i].get_attribute("innerText").strip() if i < len(details) else "No detail"

    results.append({
        "EAN": ean,
        "Product Name": name,
        "URL": url,
        "Offer Label": label,
        "Offer Detail": detail
    })

# -------------------------------
# 📊 Convert to pandas
# -------------------------------
df = pd.DataFrame(results)

print("\n✅ Final Output:")
print(df.head())

# time.sleep(10)

driver.quit()

DEBUG COUNTS:
Products: 60
Labels: 5
Details: 5

✅ Final Output:

,EAN,Product Name,URL,Offer Label,Offer Detail
0,3600524049102,Morphy Richards 10204 Kettle in Navy,https://www.superdrug.com/electricals/kitchen-...,Save up to ½ price,Save up to ½ price on Morphy Richards!
1,3600524049102,Morphy Richards 400520 Compact Stand Mixer in ...,https://www.superdrug.com/electricals/kitchen-...,Save up to ½ price,Save up to ½ price on Morphy Richards!
2,3600524049102,Boost Oxygen Supplemental Oxygen Canister - Na...,https://www.superdrug.com/health/general-wellb...,Buy 6 & Save,Buy 6 and save 25% (Any 5L Canisters)
3,3600524049102,Fila Green SFI458 52 5206W5 Sunglasses,https://www.superdrug.com/fashion/menswear/men...,Buy 2 & Save,Buy 2 and save 10% (Any 5L Canisters)
4,3600524049102,Bodhi RPET 500ml Water Bottle,https://www.superdrug.com/toiletries/travel-si...,Buy 3 & Save,Buy 3 and save 14% (Any 5L Canisters)
5,3600524049102,Carrera Blue 5036 49 S VV1 8E Sunglasses,https://www.superdrug.com/fashion/womenswear/w...,No offer,No detail
6,3600524049102,Burberry Black BE4405F 51 300187 Fashion Sungl...,https://www.superdrug.com/fashion/womenswear/w...,No offer,No detail
7,3600524049102,Carrera Beige 5048 51 S 003 51 Sunglasses,https://www.superdrug.com/fashion/womenswear/w...,No offer,No detail
8,3600524049102,Converse Grey CV520S RISE UP 55 360 Sunglasses,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
9,3600524049102,Fila Grey SF202 63 63C5 Sunglasses,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
10,3600524049102,Bodhi RPET 500ml Water Bottle,https://www.superdrug.com/toiletries/travel-si...,No offer,No detail
11,3600524049102,Karl Lagerfeld Grey-Blue KL6102S 56 525 Sungla...,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
12,3600524049102,Converse Blue CV507S MALDEN 52 102 Sunglasses,https://www.superdrug.com/fashion/womenswear/w...,No offer,No detail
13,3600524049102,Carrera Blue CA8056 51 S 900 Sunglasses,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
14,3600524049102,Nike Green CLOAK EV24005 57 5720100 Sunglasses,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
15,3600524049102,Police Grey SPLL80 52 520836 Sunglasses,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
16,3600524049102,Bodhi RPET 500ml Water Bottle,https://www.superdrug.com/toiletries/travel-si...,No offer,No detail
17,3600524049102,Calvin Klein Green CK19316S 60 045 Fashion Sun...,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
18,3600524049102,Active Era 320 Piece Premium First Aid Kit Bag,https://www.superdrug.com/health/first-aid/fir...,No offer,No detail
19,3600524049102,Timberland Black TB9130 52 5202R Sunglasses,https://www.superdrug.com/fashion/womenswear/w...,No offer,No detail
20,3600524049102,Adidas Blue AOR030 52 021 0 Sunglasses,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
21,3600524049102,Carta Sport Water Bottle (0.5L),https://www.superdrug.com/toiletries/travel-si...,No offer,No detail
22,3600524049102,Converse Pink CV305S NORTH END 51 780 Sunglasses,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
23,3600524049102,Fila Blue SFI300 58 580K53 Sunglasses,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
24,3600524049102,Carolina Herrera Pink CH 0010 52 S LHF Sunglasses,https://www.superdrug.com/fashion/womenswear/w...,No offer,No detail
25,3600524049102,Timberland Black TB9157 52 5202D Sunglasses,https://www.superdrug.com/fashion/womenswear/w...,No offer,No detail
26,3600524049102,Lanvin Blue LNV104S 56 050 Sunglasses,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
27,3600524049102,Converse Blue CV505S CHUCK 56 100 Sunglasses,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
28,3600524049102,Oregon Recycled Plastic 400ml Carabiner Water ...,https://www.superdrug.com/toiletries/travel-si...,No offer,No detail
29,3600524049102,Bjorn Borg 5 Pack Cotton Stretch Boxer ASS2,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
30,3600524049102,Bullet Bodhi Glass 500ml Sports Bottle,https://www.superdrug.com/toiletries/travel-si...,No offer,No detail
31,3600524049102,Police Orange SPL343 52 52M03G Sunglasses,https://www.superdrug.com/fashion/womenswear/w...,No offer,No detail
32,3600524049102,Oregon Recycled Plastic 400ml Carabiner Water ...,https://www.superdrug.com/toiletries/travel-si...,No offer,No detail
33,3600524049102,Oregon Recycled Plastic 400ml Carabiner Water ...,https://www.superdrug.com/toiletries/travel-si...,No offer,No detail
34,3600524049102,Converse Blue CV503S DISRUPT 52 260 Sunglasses,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
35,3600524049102,Karl Lagerfeld Green KL6102S 56 300 Sunglasses,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
36,3600524049102,Converse Blue CV506S CHUCK 57 102 Sunglasses,https://www.superdrug.com/fashion/womenswear/w...,No offer,No detail
37,3600524049102,Oregon Recycled Plastic 400ml Carabiner Water ...,https://www.superdrug.com/toiletries/travel-si...,No offer,No detail
38,3600524049102,Carrera Grey CA236S 54 0V81 IR Fashion Sunglasses,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
39,3600524049102,Quadra Water Bottle and Holder,https://www.superdrug.com/toiletries/travel-si...,No offer,No detail
40,3600524049102,Bodhi RPET 500ml Water Bottle,https://www.superdrug.com/toiletries/travel-si...,No offer,No detail
41,3600524049102,Carolina Herrera NY Orange SHN051M 54 5408FC S...,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
42,3600524049102,Fila Blue SFI085 50 500R22 Sunglasses,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
43,3600524049102,Fila Grey SF 202 63 C6 Sunglasses,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
44,3600524049102,Spring Copper 500ml Insulated Water Bottle,https://www.superdrug.com/toiletries/travel-si...,No offer,No detail
45,3600524049102,Adidas Blue AOR030 52 012 0 Sunglasses,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
46,3600524049102,Oregon Recycled Plastic 400ml Carabiner Water ...,https://www.superdrug.com/toiletries/travel-si...,No offer,No detail
47,3600524049102,Calvin Klein Blue CK20518S 60 410 Fashion Sung...,https://www.superdrug.com/fashion/womenswear/w...,No offer,No detail
48,3600524049102,Oregon Recycled Plastic 400ml Carabiner Water ...,https://www.superdrug.com/toiletries/travel-si...,No offer,No detail
49,3600524049102,Bodhi RPET 500ml Water Bottle,https://www.superdrug.com/toiletries/travel-si...,No offer,No detail
50,3600524049102,Carrera Grey CA1035GS 58 0010 IR Fashion Sungl...,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
51,3600524049102,Adidas Multicoloured AOR005 54 PDC 30 Sunglasses,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
52,3600524049102,Nike Brown RADEON 2 FV2405 52 5220004 Sunglasses,https://www.superdrug.com/fashion/menswear/men...,No offer,No detail
53,3600524049102,Timberland Grey TB9157 52 5255D Sunglasses,https://www.superdrug.com/fashion/womenswear/w...,No offer,No detail
54,3600524049102,Bebo Plastic 500ml Water Bottle,https://www.superdrug.com/toiletries/travel-si...,No offer,No detail
55,3600524049102,Bebo Plastic 500ml Water Bottle,https://www.superdrug.com/toiletries/travel-si...,No offer,No detail
56,3600524049102,Police Pink SPLD31 56 560300 Sunglasses,https://www.superdrug.com/fashion/womenswear/w...,No offer,No detail
57,3600524049102,The House of Puzzles Tight Corner Jigsaw Puzzle,https://www.superdrug.com/gift-shop/novelty-gi...,No offer,No detail
58,3600524049102,Michael Kors Grey MK2104 62 32466G Sunglasses,https://www.superdrug.com/fashion/womenswear/w...,No offer,No detail
59,3600524049102,Active Era 180 Piece First Aid Kit Refill,https://www.superdrug.com/health/first-aid/fir...,No offer,No detail

### Resolve for 1 Product Multiple offers

In [ ]:
# Using global label indexing is leaking promotion codes to other product ids.

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

import pandas as pd
import time

# -------------------------------
# 🔒 Setup Chrome
# -------------------------------
chrome_options = Options()
chrome_options.add_argument("--disable-notifications")
chrome_options.add_experimental_option(
    "prefs", {"profile.default_content_setting_values.notifications": 2}
)

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=chrome_options
)

wait = WebDriverWait(driver, 15)

# -------------------------------
# 🔍 Input
# -------------------------------
ean = "3600524049102"

# -------------------------------
# 🌐 Open Website
# -------------------------------
driver.get("https://www.superdrug.com")

# Accept cookies
try:
    wait.until(EC.element_to_be_clickable(
        (By.XPATH, "//button[contains(text(),'Accept')]"))
    ).click()
except:
    pass

# -------------------------------
# 🔍 Perform Search
# -------------------------------
search_box = wait.until(
    EC.presence_of_element_located(
        (By.XPATH, "//input[@role='combobox' and @aria-label='Search']")
    )
)

search_box.clear()
search_box.send_keys(ean)
search_box.send_keys(Keys.RETURN)

# Wait for product cards
wait.until(EC.presence_of_element_located(
    (By.XPATH, "//div[contains(@class,'product-list-item')]"))
)

# Remove chat popup
driver.execute_script("""
var elem = document.getElementById('toky_container');
if (elem) { elem.remove(); }
""")

# Scroll to trigger lazy loading
driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
time.sleep(3)

# -------------------------------
# 🧠 Extract products + promotions
# -------------------------------
products = driver.find_elements(
    By.XPATH, "//div[contains(@class,'product-list-item')]"
)

results = []

for p in products:

    # -------------------------------
    # ✅ Validate product (avoid ghost rows)
    # -------------------------------
    name_elements = p.find_elements(
        By.XPATH, ".//a[contains(@class,'cx-product-name')]"
    )

    if not name_elements:
        continue

    name = name_elements[0].get_attribute("innerText").strip()

    if not name:
        continue

    url = name_elements[0].get_attribute("href")

    if not url:
        continue

    # -------------------------------
    # 🔥 Extract promotions (multiple)
    # -------------------------------
    promo_blocks = p.find_elements(By.XPATH, ".//e2-promotion")

    valid_promo_found = False

    for block in promo_blocks:

        try:
            label = block.find_element(
                By.XPATH, ".//span[contains(@class,'promotion__offer-label')]"
            ).get_attribute("innerText").strip()
        except:
            label = ""

        try:
            detail = block.find_element(
                By.XPATH, ".//div[contains(@class,'promotion__label')]"
            ).get_attribute("innerText").strip()
        except:
            detail = ""

        # ❌ Skip empty promotions
        if not label and not detail:
            continue

        valid_promo_found = True

        results.append({
            "EAN": ean,
            "Product Name": name,
            "URL": url,
            "Offer Label": label,
            "Offer Detail": detail
        })

    # ❌ Skip products with no valid promotions
    if not valid_promo_found:
        continue

# -------------------------------
# 📊 Convert to pandas
# -------------------------------
df = pd.DataFrame(results)

# Remove duplicates (extra safety)
df = df.drop_duplicates(subset=["Product Name", "URL", "Offer Label", "Offer Detail"])

print("\n✅ FINAL CLEAN OUTPUT:")
print(df.head())

driver.quit()

✅ FINAL CLEAN OUTPUT:
             EAN                                       Product Name  \
0  3600524049102  Maybelline Fit Me Matte & Poreless Powder 105 ...
1  3600524049102  Maybelline Fit Me Matte & Poreless Powder 105 ...
4  3600524049102               Morphy Richards 10204 Kettle in Navy
6  3600524049102  New Leaf CoQ10 200mg - Co Enzyme Pure Ubiquino...
8  3600524049102  APIS Strengthening Anti-Hair Loss Conditioner ...

                                                 URL  \
0  https://www.superdrug.com/make-up/face/face-po...
1  https://www.superdrug.com/make-up/face/face-po...
4  https://www.superdrug.com/electricals/kitchen-...
6  https://www.superdrug.com/health/vitamins-supp...
8  https://www.superdrug.com/hair/everyday-condit...

                                 Offer Label  \
0  Free next day delivery when you spend £25
1                                    3 for 2
4                         Save up to ½ price
6                               Buy 3 & Save
8                                  £5 Friday

                                        Offer Detail
0  Free Next Day Delivery when you spend £25 on s...
1                     3 for 2 on selected Maybelline
4             Save up to ½ price on Morphy Richards!
6  Purchase 3 Or More New Leaf Products And Get 1...
8  £5 Friday | Enjoy £5 Prices on Selected Apis N...

In [42]:
df.head(40)

,EAN,Product Name,URL,Offer Label,Offer Detail
0,3600524049102,Maybelline Fit Me Matte & Poreless Powder 105 ...,https://www.superdrug.com/make-up/face/face-po...,Free next day delivery when you spend £25,Free Next Day Delivery when you spend £25 on s...
1,3600524049102,Maybelline Fit Me Matte & Poreless Powder 105 ...,https://www.superdrug.com/make-up/face/face-po...,3 for 2,3 for 2 on selected Maybelline
4,3600524049102,Morphy Richards 10204 Kettle in Navy,https://www.superdrug.com/electricals/kitchen-...,Save up to ½ price,Save up to ½ price on Morphy Richards!
6,3600524049102,New Leaf CoQ10 200mg - Co Enzyme Pure Ubiquino...,https://www.superdrug.com/health/vitamins-supp...,Buy 3 & Save,Purchase 3 Or More New Leaf Products And Get 1...
8,3600524049102,APIS Strengthening Anti-Hair Loss Conditioner ...,https://www.superdrug.com/hair/everyday-condit...,£5 Friday,£5 Friday | Enjoy £5 Prices on Selected Apis N...
10,3600524049102,Magnesium Supplement 516mg with Zinc - 120s Hi...,https://www.superdrug.com/health/vitamins-supp...,Buy 3 & Save,Purchase 3 Or More New Leaf Products And Get 1...
12,3600524049102,APIS Home Terapis Cleansing Gel with Active Ca...,https://www.superdrug.com/skin/face-skin-care/...,£5 Friday,£5 Friday | Enjoy £5 Prices on Selected Apis N...
14,3600524049102,Morphy Richards 400520 Compact Stand Mixer in ...,https://www.superdrug.com/electricals/kitchen-...,Save up to ½ price,Save up to ½ price on Morphy Richards!
16,3600524049102,Boost Oxygen Supplemental Oxygen Canister - Na...,https://www.superdrug.com/health/general-wellb...,Buy 6 & Save,Buy 6 and save 25% (Any 5L Canisters)
17,3600524049102,Boost Oxygen Supplemental Oxygen Canister - Na...,https://www.superdrug.com/health/general-wellb...,Buy 2 & Save,Buy 2 and save 10% (Any 5L Canisters)
18,3600524049102,Boost Oxygen Supplemental Oxygen Canister - Na...,https://www.superdrug.com/health/general-wellb...,Buy 3 & Save,Buy 3 and save 14% (Any 5L Canisters)

In [ ]:
# Learn pagination with Selenium
# Learn multiprocessing vs multithreading

# Search for web Voyager - vision base web browsing capable of controllling mouse and keyboard
# Set of marks concept
# Complete guide to AsyncIO in python

## Crawl4AI Basics